---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '12:00'
      timezone: 'Europe/Rome'
    commit-message:
      prefix: 'build(deps):'
    labels:
      - 'dependabot'
